export const ControlKind = {
    window: "window",
    menuBar: "menuBar",
    menuItem: "menuItem",
    menuItemEntry: "menuItemEntry",
    contextBar: "contextBar",
    toolStrip: "toolStrip",
    toolButton: "toolButton",
    docBar: "docBar",
    view: "view",
    dock: "dock",
    panel: "panel",
    panelContainer: "panelContainer",
    grid: "grid",
    canvas: "canvas",
    statusBar: "statusBar",
    element: "element",
    text: "text",
    label: "label",
    textBox: "textBox",
    button: "button",
    checkBox: "checkBox",
    radioButton: "radioButton",
    flowLayoutPanel: "flowLayoutPanel",
    tableLayoutPanel: "tableLayoutPanel",
    groupBox: "groupBox",
    splitContainer: "splitContainer",
    comboBox: "comboBox",
    listBox: "listBox",
    progressBar: "progressBar",
    trackBar: "trackBar",
    tabControl: "tabControl",
    tabPage: "tabPage",
    diagnosticsPanel: "diagnosticsPanel",
    messageBox: "messageBox",
    layoutCanvas: "layoutCanvas",
    toolbox: "toolbox",
    switchButton: "switchButton"
} as const;

export type ControlKind = (typeof ControlKind)[keyof typeof ControlKind];
