export type IconType = "font" | "css" | "class";

export type IconSet = {
    id: string;
    label: string;
    type: IconType;
    icons: Record<string, string>;
};

const iconNames = [
    "new",
    "edit",
    "delete",
    "import",
    "export",
    "save",
    "saveAs",
    "open",
    "close",
    "exit",
    "hand",
    "pin",
    "search",
    "filter",
    "sort",
    "refresh",
    "settings",
    "preferences",
    "info",
    "help",
    "warning",
    "error",
    "confirm",
    "success",
    "add",
    "remove",
    "copy",
    "paste",
    "cut",
    "undo",
    "redo",
    "print",
    "lock",
    "unlock",
    "user",
    "users",
    "contact",
    "phone",
    "email",
    "calendar",
    "clock",
    "map",
    "location",
    "home",
    "folder",
    "file",
    "link",
    "unlink",
    "attach",
    "upload",
    "download",
    "play",
    "pause",
    "stop",
    "record",
    "next",
    "previous",
    "first",
    "last",
    "volume",
    "mute",
    "chat",
    "comment",
    "star",
    "tag",
    "bookmark",
    "list",
    "grid",
    "table",
    "graph",
    "chart",
    "pie",
    "bar",
    "lineChart",
    "camera",
    "image",
    "video",
    "music",
    "key",
    "shield",
    "bell",
    "notification",
    "flag",
    "check",
    "x",
    "question",
    "tools",
    "diagnostics",
    "bug",
    "trash",
    "zoomIn",
    "zoomOut",
    "maximize",
    "minimize",
    "restore",
    "window",
    "about",
    "helpDocs",
    "sync",
    "database",
    "server",
    "api",
    "chevronLeft",
    "chevronRight"
];

const buildMap = (defaultValue: string, overrides: Record<string, string>) => {
    const map: Record<string, string> = {};
    iconNames.forEach((name) => {
        map[name] = overrides[name] ?? defaultValue;
    });
    return map;
};

const retroOverrides = {
    new: "rect",
    edit: "select",
    delete: "line",
    import: "image",
    export: "image",
    save: "rect",
    open: "rect",
    close: "line",
    exit: "hand",
    hand: "hand",
    pin: "rect",
    search: "zoom",
    settings: "polygon",
    preferences: "polygon",
    info: "text",
    help: "text",
    warning: "bind",
    error: "line",
    confirm: "bind",
    success: "ellipse",
    phone: "hand",
    email: "bind",
    diagnostics: "bind",
    bug: "bind",
    zoomIn: "zoom",
    zoomOut: "zoom",
    window: "rect"
};

const materialOverrides = {
    new: "person_add",
    edit: "edit",
    delete: "delete",
    import: "upload_file",
    export: "download",
    save: "save",
    saveAs: "save_as",
    open: "folder_open",
    close: "close",
    hand: "pan_tool_alt",
    pin: "push_pin",
    exit: "logout",
    search: "search",
    filter: "filter_alt",
    sort: "sort",
    refresh: "refresh",
    settings: "settings",
    preferences: "settings",
    info: "info",
    help: "help",
    warning: "warning",
    error: "error",
    confirm: "help",
    success: "check_circle",
    add: "add",
    remove: "remove",
    copy: "content_copy",
    paste: "content_paste",
    cut: "content_cut",
    undo: "undo",
    redo: "redo",
    print: "print",
    lock: "lock",
    unlock: "lock_open",
    user: "person",
    users: "group",
    contact: "contact_page",
    phone: "call",
    email: "email",
    calendar: "calendar_month",
    clock: "schedule",
    map: "map",
    location: "location_on",
    home: "home",
    folder: "folder",
    file: "description",
    link: "link",
    unlink: "link_off",
    attach: "attach_file",
    upload: "upload",
    download: "download",
    play: "play_arrow",
    pause: "pause",
    stop: "stop",
    record: "fiber_manual_record",
    next: "skip_next",
    previous: "skip_previous",
    first: "first_page",
    last: "last_page",
    volume: "volume_up",
    mute: "volume_off",
    chat: "chat",
    comment: "comment",
    star: "star",
    tag: "sell",
    bookmark: "bookmark",
    list: "list",
    grid: "grid_view",
    table: "table_view",
    graph: "timeline",
    chart: "bar_chart",
    pie: "pie_chart",
    bar: "bar_chart",
    lineChart: "show_chart",
    camera: "photo_camera",
    image: "image",
    video: "videocam",
    music: "music_note",
    key: "key",
    shield: "shield",
    bell: "notifications",
    notification: "notifications",
    flag: "flag",
    check: "check",
    x: "close",
    question: "help",
    tools: "build",
    diagnostics: "bug_report",
    bug: "bug_report",
    trash: "delete",
    zoomIn: "zoom_in",
    zoomOut: "zoom_out",
    maximize: "open_in_full",
    minimize: "minimize",
    restore: "close_fullscreen",
    window: "crop_square",
    about: "info",
    helpDocs: "help",
    sync: "sync",
    database: "database",
    server: "dns",
    api: "api",
    chevronLeft: "chevron_left",
    chevronRight: "chevron_right"
};

const bootstrapOverrides = {
    new: "person-plus",
    edit: "pencil",
    delete: "trash",
    import: "file-earmark-arrow-up",
    export: "file-earmark-arrow-down",
    save: "save",
    saveAs: "save2",
    open: "folder2-open",
    close: "x",
    hand: "hand-index",
    pin: "pin-angle",
    exit: "box-arrow-right",
    search: "search",
    filter: "funnel",
    sort: "sort-down",
    refresh: "arrow-clockwise",
    settings: "gear",
    preferences: "gear",
    info: "info-circle",
    help: "question-circle",
    warning: "exclamation-triangle",
    error: "x-circle",
    confirm: "question-circle",
    success: "check-circle",
    add: "plus",
    remove: "dash",
    copy: "files",
    paste: "clipboard",
    cut: "scissors",
    undo: "arrow-counterclockwise",
    redo: "arrow-clockwise",
    print: "printer",
    lock: "lock",
    unlock: "unlock",
    user: "person",
    users: "people",
    contact: "person-lines-fill",
    phone: "telephone",
    email: "envelope",
    calendar: "calendar",
    clock: "clock",
    map: "map",
    location: "geo-alt",
    home: "house",
    folder: "folder",
    file: "file-earmark",
    link: "link-45deg",
    unlink: "link-45deg",
    attach: "paperclip",
    upload: "upload",
    download: "download",
    play: "play",
    pause: "pause",
    stop: "stop",
    record: "record-circle",
    next: "skip-forward",
    previous: "skip-backward",
    first: "skip-backward",
    last: "skip-forward",
    volume: "volume-up",
    mute: "volume-mute",
    chat: "chat",
    comment: "chat-dots",
    star: "star",
    tag: "tag",
    bookmark: "bookmark",
    list: "list",
    grid: "grid",
    table: "table",
    graph: "graph-up",
    chart: "bar-chart",
    pie: "pie-chart",
    bar: "bar-chart",
    lineChart: "graph-up",
    camera: "camera",
    image: "image",
    video: "camera-video",
    music: "music-note",
    key: "key",
    shield: "shield",
    bell: "bell",
    notification: "bell",
    flag: "flag",
    check: "check",
    x: "x",
    question: "question-circle",
    tools: "tools",
    diagnostics: "bug",
    bug: "bug",
    trash: "trash",
    zoomIn: "zoom-in",
    zoomOut: "zoom-out",
    maximize: "arrows-fullscreen",
    minimize: "dash",
    restore: "fullscreen-exit",
    window: "window",
    about: "info-circle",
    helpDocs: "question-circle",
    sync: "arrow-repeat",
    database: "database",
    server: "server",
    api: "braces",
    chevronLeft: "chevron-left",
    chevronRight: "chevron-right"
};

const iconSets: Record<string, IconSet> = {
    chicago95: {
        id: "chicago95",
        label: "Chicago95 (Retro)",
        type: "css",
        icons: buildMap("select", retroOverrides)
    },
    famfamfam: {
        id: "famfamfam",
        label: "FamFamFam (Retro)",
        type: "css",
        icons: buildMap("select", retroOverrides)
    },
    fugue: {
        id: "fugue",
        label: "Fugue (Retro)",
        type: "css",
        icons: buildMap("select", retroOverrides)
    },
    material: {
        id: "material",
        label: "Material Symbols (Modern)",
        type: "font",
        icons: buildMap("help", materialOverrides)
    },
    bootstrap: {
        id: "bootstrap",
        label: "Bootstrap Icons (Modern)",
        type: "class",
        icons: buildMap("question-circle", bootstrapOverrides)
    }
};

let activeIconSetId = "material";

export const listIconNames = () => [...iconNames];

export const listIconSets = () => Object.values(iconSets);

export const setActiveIconSet = (id: string) => {
    if (iconSets[id]) {
        activeIconSetId = id;
    }
};

export const getActiveIconSet = () => activeIconSetId;

export const resolveIconDefinition = (name?: string) => {
    if (!name) return undefined;
    const set = iconSets[activeIconSetId] ?? iconSets.material;
    const value = set.icons[name];
    if (!value) return undefined;
    return { type: set.type, value } as { type: IconType; value: string };
};