<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/StreamCraft.Core/StreamCraft.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bit.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="ui\dist\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="sql\migrations\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>







